// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package access

import (
	"database/sql"
)

type Recipie struct {
	ID          int64
	Name        string
	Ingredients sql.NullString
	Directions  sql.NullString
}
